using UnityEngine;
using NativeWebSocket;
using System;
using System.Text;

public class ChatSocketManager : MonoBehaviour
{
    public static ChatSocketManager Instance { get; set; }
    private WebSocket websocket;

    public bool IsConnected => websocket != null && websocket.State == WebSocketState.Open;

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
        DontDestroyOnLoad(gameObject);
    }
    
    public async void Init(string token, int playerId)
    {
        string url = $"{GameConfig.ChatSocketUrl}?playerId={playerId}&token={token}";

        websocket = new WebSocket(url);

        websocket.OnOpen += () =>
        {
            Debug.Log("ðŸ”Œ ChatSocket Ä‘Ã£ káº¿t ná»‘i!");
        };

        websocket.OnError += (e) =>
        {
            Debug.Log("âŒ ChatSocket lá»—i: " + e);
        };

        websocket.OnClose += (e) =>
        {
            Debug.Log("ðŸ”Œ ChatSocket Ä‘Ã³ng");
        };

        websocket.OnMessage += (bytes) =>
        {
            string message = Encoding.UTF8.GetString(bytes);
            Debug.Log("ðŸ“© Received chat: " + message);
        };

        await websocket.Connect();
    }

    void Update()
    {
        websocket?.DispatchMessageQueue();
    }

    public async void SendChatMessage(string message)
    {
        if (websocket.State == WebSocketState.Open)
        {
            await websocket.SendText(message);
        }
    }

    private async void OnApplicationQuit()
    {
        await websocket.Close();
    }
}
